### ISSUE TITLE
这代码你自己都没跑过吧，那么多格式错误

### ISSUE THREAD

**Issue by Faora** [ShulinCao/OpenNRE-PyTorch#1]

**Comment by ShulinCao** [comment]
额，我跑的没问题，你是啥格式错误

**Comment by Faora** [comment]
> 额，我跑的没问题，你是啥格式错误

![image](https://user-images.githubusercontent.com/42265843/46724348-67a35a00-ccac-11e8-8cf6-8edbf8858016.png)
Config.py
这么明显的格式错误
还有别的地方

**Comment by Faora** [comment]
> 额，我跑的没问题，你是啥格式错误

![image](https://user-images.githubusercontent.com/42265843/46724475-afc27c80-ccac-11e8-9afc-59c705ccbcfa.png)
encoder.py

**Comment by ShulinCao** [comment]
为啥我自己的编辑器显示没有问题，代码也能运行，一push到缩进就不对了
![image](https://user-images.githubusercontent.com/19309481/46725343-90c4ea00-ccae-11e8-9ea6-5d613e9c49c8.png)
