### ISSUE TITLE
Why set two embedding tables for attention?

### ISSUE THREAD

**Issue by LifangD** [ShulinCao/OpenNRE-PyTorch#12]
您好，想请教一下为什么attention的设置中既有relation_matrix 又有attention_matrix呢？论文里或者别的一些实现里只用了一个relation 的embedding, e,g: 
![image](https://user-images.githubusercontent.com/33337947/54806516-2da39e80-4cb5-11e9-9c8e-98f49247e32c.png)

**Comment by ShulinCao** [comment]
你可以试下，其实两个效果差别不大，原论文里其实是relation和query各一个matrix

**Comment by LifangD** [comment]
确实应该差不多，您是说这里的r 和 M 不是来自同一个matrix ? 还有您的code里面attention matrix 想要表达的是A？ 不知道为什么这里的weighted diagonal matrix A 其他实现好像也没有特别强调...
![image](https://user-images.githubusercontent.com/33337947/54813149-dc50da80-4cc7-11e9-9024-46d802aacd93.png)
  ![image](https://user-images.githubusercontent.com/33337947/54813155-e1ae2500-4cc7-11e9-94de-42157d5ba2ef.png)
@ShulinCao

**Comment by ShulinCao** [comment]
按论文里，有一个M和一个A,r是来自M

**Comment by LifangD** [comment]
thx~~
