### ISSUE TITLE
Relation extraction for a given sentence

### ISSUE THREAD

**Issue by taufique74** [ShulinCao/OpenNRE-PyTorch#20]
Is there any way to extract relation for a sentence given as an input?
I wanted to write an interface so that I can extract relations as a tuple for a given sentence, any hint?

**Comment by ShulinCao** [comment]
Hi,
In selector.test function, 
https://github.com/ShulinCao/OpenNRE-PyTorch/blob/11bf7ce0aa5ac6ef168e43065722fb3cad2a14b4/networks/selector.py#L63
you can get the score for each relation, than you can get the most possible relation for one sentence and map the index to the relation label.

**Comment by taufique74** [comment]
@ShulinCao thanks so much!
