### ISSUE TITLE
关于运行结果的问题

### ISSUE THREAD

**Issue by DexterZeng** [ShulinCao/OpenNRE-PyTorch#3]
你好 谢谢提供Pytorch的代码版本！
请问一下 为什么我实现出来的结果最高的也只有0.8呢？
![0 01-100](https://user-images.githubusercontent.com/14938032/48301209-1a254180-e525-11e8-8e36-0b55856f5783.png)

**Comment by ShulinCao** [comment]
你用的参数是啥

**Comment by DexterZeng** [comment]
就是程序原本的参数啊【捂脸】

**Comment by ShulinCao** [comment]
不太清楚，你每次都是这样吗

**Comment by DexterZeng** [comment]
嗯 就用的原本参数 跑出来结果就这样 我再看看吧
