### ISSUE TITLE
关于attention

### ISSUE THREAD

**Issue by ShangYuming** [ShulinCao/OpenNRE-PyTorch#7]
您好，非常感谢您分享的代码。我有个小问题，在selector   44行
`for i in range(len(self.scope) - 1)`
这个地方应该是按照bag进行attention，为什么要-1少取一个scope呢？
谢谢，祝新年快乐

**Comment by ShulinCao** [comment]
第45行有 
sen_matrix = x[self.scope[i] : self.scope[i + 1]]
举个例子，有三个bag, 分别有2，3，4个instance, 则x的内容是[0,2,5,9]

**Comment by ShangYuming** [comment]
非常感谢。还有一个小问题，就是在bag上面的attention的query应该是bag的label，可是我看代码中用的query是instence的label。小白刚开始，还请不吝赐教。。。

**Comment by ShulinCao** [comment]
用的是bag的label，你看的是哪行代码

**Comment by ShangYuming** [comment]
您好，在Config中，第119行
`self.data_query_label = np.load(os.path.join(self.data_path, 'train_ins_label.npy'))`
这里面的ins_label是sentence的label
打扰了，万分感谢
